openapi: 3.0.0
info:
  version: '1.0'
  title: 'Maxstore'
  license:
    name: MIT
servers:
  - url: 'localhost:3000'
paths:
  /user:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /products:
    get:
      summary: 'Получает список продуктов'
      operationId: listProducts
      tags:
        - products
      parameters:
        - name: id
          in: query
          description: ID продукта
          required: true
          schema:
            type: integer
            format: int32
        - name: name
          in: query
          description: Имя или чать имени продукта
          required: true
          schema:
            type: integer
            format: int32
        - name: sort
          in: query
          description: название поля сортировки и направление
          required: true
          schema:
            type: string
            enum:
              - name
              - price
        - name: filter
          in: query
          description: название и значения полей фильтров
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Информация списка продуктов'
          headers:
            x-next:
              description: Переход на следующую страницу
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Products:
      title: Данные по сотрудникам
      type: array
      description: 'массив данных по сотрудникам/физлицам, их карьере и отсутствиям'
      items:
        $ref: '#/components/schemas/Product'
    Product:
      title: Профиль АХО
      required:
        - ID
        - Name
      type: object
      properties:
        ID:
          title: Идентификатор
          type: string
          format: guid
          example: 159eb148-c46b-11e7-8111-00155da00e02
        Name:
          title: Наименование
          type: string
          example: Профиль 110
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []